### ISSUE TITLE
Why cant I add corner radius to Button and background view color? Please add an example with corner radius.

### ISSUE THREAD

**Issue by ajith15216** [CRED-CLUB/neopop-ios#13]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ajithaisle** [comment]
I want to use Neopop library with corner radius to Button but the UI doesn't look good after adding corner raidus.

**Comment by ghost** [comment]
@ajithaisle we don't support buttons with corner radius yet.
